spring:
  application:
    name: fanfare
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #  logging:
  #    level:
  #      org:
  #        springframework:
  #          security=DEBUG:
  jwt:
    secret: ${JWT_SECRET_KEY}
