{{- if not .Values.env.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fan-fare-be.fullname" . }}-secret
  labels:
    {{- include "fan-fare-be.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.env }}
  {{- if and (ne $key "existingSecret") (ne $value "") }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
