replicaCount: 2

image:
  registry: docker.io
  repository: ""
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

livenessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  tcpSocket:
    port: 8080
  initialDelaySeconds: 20
  periodSeconds: 5

podAnnotations: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

env:
  existingSecret: ""
  DB_HOST: ""
  DB_PORT: "5432"
  DB_NAME: ""
  DB_USERNAME: ""
  DB_PASSWORD: ""
  JWT_SECRET_KEY: ""
